str=input("enter the string :")
str=str.lower()
print(f"Number of vowels:{str.count('a')+str.count('e')+str.count('i')+str.count('o')+str.count('u')}")
            #or
str1=input("enter the string :")
str1=str1.lower()
a=str1.count('a')
e=str1.count('e')
i=str1.count('i')
o=str1.count('o')
u=str1.count('u')
print(f"Number of vowels:{a+e+i+o+u}")